hitsTitles = ['BROTHERS IN ARMS','BOHEMIAN RHAPSODY','STAIRWAY TO HEAVEN','RAIDERS ON THE STORM','WISH YOU WERE HERE']
hitsTitles.append('CHILD IN TIME')
hitsTitles.append('AGAIN')
print(hitsTitles)
hitsTitles.insert(2,'HOTEL CALIFORNIA')
print(hitsTitles)
hitsTitles.insert(0,'THE SOUND OF SILENCE')
print(hitsTitles)
print(hitsTitles.index('HOTEL CALIFORNIA'))
hitsTitles.remove('HOTEL CALIFORNIA')
print(hitsTitles)
hitsTitles[0]='ENJOY THE SILENCE'
print(hitsTitles)
hitsToRead = hitsTitles.copy()
hitsToRead.sort()
print(hitsToRead)
print(hitsToRead.pop(0))
print(hitsToRead.pop(0))
additionalSongs = ['NOTHING COMPARES 2 U','WISH YOU WERE HERE']
hitsToRead.extend(additionalSongs)
print(hitsToRead)
print(hitsToRead.count('WISH YOU WERE HERE'))
print(hitsToRead.count('RIDERS OF THE STORM'))
hitsToRead.clear()
print(hitsToRead)

countries = ['POL', 'CZE', 'SLK']
print(countries)
print(countries[1])
countries[2] = 'RUM'
print(countries)
countries.append('AUS')
print(countries)
countries.insert(1,'SER')
print(countries)
countries.remove('RUM')
print(countries)
countries.sort()
print(countries)
countries.reverse()
print(countries)
print(countries.pop(1))
print(countries)
print(countries.index('AUS'))
print(countries.count('CZE'))
newList = ['NOR','DAN']
countries.extend(newList)
print(countries)
countries = countries.copy()

Tax = (9, 3)
print(Tax)